apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
        - name: graylog
          image: graylog/graylog:4.2
          ports:
            - containerPort: 9000
            - containerPort: 12201
          env:
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: http://localhost:9000/
            - name: GRAYLOG_PASSWORD_SECRET
              value: KQjC^Fn^d3k^9eG)CS3PCk$3AT$W6cp6mqE#+NMqefcyYSkS#mNp+)j5ktZ3Yc$3
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            - name: GRAYLOG_HTTP_ENABLE_CORS
              value: "true"
            - name: GRAYLOG_HTTP_CORS_ALLOW_ORIGIN
              value: "*"
            - name: GRAYLOG_ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: GRAYLOG_MONGO_URI
              value: mongodb://mongo:27017/graylog
---
apiVersion: v1
kind: Service
metadata:
  name: graylog-service
spec:
  type: NodePort
  ports:
    - name: web
      port: 9000
      targetPort: 9000
      nodePort: 32000
    - name: gelf-tcp
      port: 12201
      targetPort: 12201
      nodePort: 32001
    - name: gelf-udp
      port: 12201
      targetPort: 12201
      protocol: UDP
      nodePort: 32002
  selector:
    app: graylog
