apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: rafaelloureioc/notificationpb:10.0
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  selector:
    app: notifications
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
